/**
 * Created by robertzzy on 09/07/16.
 */

//Resource Query

export const EXERCISE_SEARCH_RESULT_RECEIVED = 'EXERCISE_SEARCH_RESULT_RECEIVED';

export const EQUIPMENT_SEARCH_RESULT_RECEIVED = 'EQUIPMENT_SEARCH_RESULT_RECEIVED';

export const MUSCLE_SEARCH_RESULT_RECEIVED = 'MUSCLE_SEARCH_RESULT_RECEIVED';

export const MUSCLE_GROUP_SEARCH_RESULT_RECEIVED = 'MUSCLE_GROUP_SEARCH_RESULT_RECEIVED';

export const GET_ALL_MUSCLES_RECEIVED = 'GET_ALL_MUSCLES_RECEIVED';

export const GET_ALL_EQUIPMENT_RECEIVED = 'GET_ALL_EQUIPMENT_RECEIVED';

export const SELECTED_MODEL = 'SELECTED_MODEL';


//Resource Creation
export const CREATE_RESOURCE_REQUEST_SENT = 'CREATE_RESOURCE_REQUEST_SENT';

export const CREATE_RESOURCE_RESULT_ACKNOWLEDGED = 'CREATE_RESOURCE_RESULT_ACKNOWLEDGED';

export const RESOURCE_CREATED = 'RESOURCE_CREATED';


//Resource Delete
export const DELETE_RESOURCE_REQUESTED = 'DELETE_RESOURCE_REQUESTED';
export const DELETE_RESOURCE_REQUEST_SENT = 'DELETE_RESOURCE_REQUEST_SENT';
export const DELETE_REQUEST_CANCELED = 'DELETE_REQUEST_CANCELED';
export const RESOURCE_DELETED = 'RESOURCE_DELETED';
export const DELETE_RESOURCE_ERROR_ACKNOWLEDGED = 'DELETE_RESOURCE_ERROR_ACKNOWLEDGED';


//Resource Update
export const UPDATE_RESOURCE_REQUEST_SENT = 'UPDATE_RESOURCE_REQUEST_SENT';

export const UPDATE_RESOURCE_RESULT_ACKNOWLEDGED = 'UPDATE_RESOURCE_RESULT_ACKNOWLEDGED';

export const RESOURCE_UPDATED = 'RESOURCE_UPDATED';

export const RESOURCE_TO_UPDATE_CHOSEN = 'RESOURCE_TO_UPDATE_CHOSEN';

export const UPDATE_RESOURCE_REQUIREMENT_FILLED = 'UPDATE_RESOURCE_REQUIREMENT_FILLED';




